<?php

$pro_file = class_exists('\ShopEngine_Pro') ? \ShopEngine_Pro::plugin_dir(). "sample-designs/contents" : false;
$free_file = \ShopEngine::core_dir(). "sample-designs/contents";

return [
    'single' => [
        [
            'id'            => 'single-01',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Single Design 1', 'shopengine'),
            'preview_thumb' => 'contents/single/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/baby-monitor-vb605-radio/',
            'file'          => $free_file ? $free_file. '/single/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-01',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Single Design 1', 'shopengine'),
            'preview_thumb' => 'contents/single/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/baby-monitor-vb605-radio/',
            'file'          => $free_file ? $free_file. '/single/01/content.html' : '',
        ],
        [
            'id'            => 'single-02',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Single Design 2', 'shopengine'),
            'preview_thumb' => 'contents/single/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/fruit-and-berry-salads-in-jars/?shopengine_template_id=487&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/single/02/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-02',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Single Design 2', 'shopengine'),
            'preview_thumb' => 'contents/single/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/fruit-and-berry-salads-in-jars/?shopengine_template_id=487&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/single/02/content.html' : '',
        ],
        [
            'id'            => 'single-03',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 3', 'shopengine'),
            'preview_thumb' => 'contents/single/03/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/baby-monitor-vb605-radio/?shopengine_template_id=718&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/03/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-03',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 3', 'shopengine'),
            'preview_thumb' => 'contents/single/03/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/baby-monitor-vb605-radio/?shopengine_template_id=718&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/03/content.html' : '',
        ],
        [
            'id'            => 'single-04',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 4', 'shopengine'),
            'preview_thumb' => 'contents/single/04/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/baby-monitor-vb605-radio/?shopengine_template_id=1121&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/04/content.json' : '',
        ],
        [
            'id'            => 'gutengerg-single-04',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 4', 'shopengine'),
            'preview_thumb' => 'contents/single/04/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/baby-monitor-vb605-radio/?shopengine_template_id=1121&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/04/content.html' : '',
        ],
        [
            'id'            => 'single-05',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 5', 'shopengine'),
            'preview_thumb' => 'contents/single/05/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/modern-chair/?shopengine_template_id=1201&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/05/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-05',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 5', 'shopengine'),
            'preview_thumb' => 'contents/single/05/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/modern-chair/?shopengine_template_id=1201&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/05/content.html' : '',
        ],
        [
            'id'            => 'single-06',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 6', 'shopengine'),
            'preview_thumb' => 'contents/single/06/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1367&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/06/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-06',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 6', 'shopengine'),
            'preview_thumb' => 'contents/single/06/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1367&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/06/content.html' : '',
        ],
        [
            'id'            => 'single-07',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 7', 'shopengine'),
            'preview_thumb' => 'contents/single/07/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1467&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/07/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-07',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 7', 'shopengine'),
            'preview_thumb' => 'contents/single/07/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1467&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/07/content.html' : '',
        ],
        [
            'id'            => 'single-08',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 8', 'shopengine'),
            'preview_thumb' => 'contents/single/08/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1561&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/08/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-08',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 8', 'shopengine'),
            'preview_thumb' => 'contents/single/08/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1561&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/08/content.html' : '',
        ],
        [
            'id'            => 'single-09',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 9', 'shopengine'),
            'preview_thumb' => 'contents/single/09/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1613&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/09/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-09',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 9', 'shopengine'),
            'preview_thumb' => 'contents/single/09/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1613&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/09/content.html' : '',
        ],
        [
            'id'            => 'single-10',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 10', 'shopengine'),
            'preview_thumb' => 'contents/single/10/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1722&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/10/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-single-10',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 10', 'shopengine'),
            'preview_thumb' => 'contents/single/10/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/product/corporate-mid-back/?shopengine_template_id=1722&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/single/10/content.html' : '',
        ],
        [
            'id'            => 'single-11',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Single Design 11 RTL', 'shopengine'),
            'preview_thumb' => 'contents/single/11/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/product/kitchen-appliances-with-wood/',
            'file'          => $pro_file ? $pro_file. '/single/11/content.json' : '',
        ],
    ],
    'archive' => [
        [
            'id'            => 'archive-01',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Archive Design 1', 'shopengine'),
            'preview_thumb' => 'contents/archive/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=158&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/archive/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-archive-01',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Archive Design 1', 'shopengine'),
            'preview_thumb' => 'contents/archive/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=158&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/archive/01/content.html' : '',
        ],
        [
            'id'            => 'archive-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Archive Design 2', 'shopengine'),
            'preview_thumb' => 'contents/archive/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=512&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/archive/02/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-archive-02',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Archive Design 2', 'shopengine'),
            'preview_thumb' => 'contents/archive/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=512&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/archive/02/content.html' : '',
        ],
        [
            'id'            => 'archive-03',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Archive Design 3 RTL', 'shopengine'),
            'preview_thumb' => 'contents/archive/03/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3871&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/archive/03/content.json' : '',
        ],
    ],
    'shop' => [
        [
            'id'            => 'shop-01',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Shop Design 1', 'shopengine'),
            'preview_thumb' => 'contents/shop/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=135&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/shop/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-shop-01',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Shop Design 1', 'shopengine'),
            'preview_thumb' => 'contents/shop/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=135&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/shop/01/content.html' : '',
        ],
        [
            'id'            => 'shop-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Shop Design 2', 'shopengine'),
            'preview_thumb' => 'contents/shop/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=444&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/02/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-shop-02',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Shop Design 2', 'shopengine'),
            'preview_thumb' => 'contents/shop/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=444&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/02/content.html' : '',
        ],
        [
            'id'            => 'shop-03',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Shop Design 3', 'shopengine'),
            'preview_thumb' => 'contents/shop/03/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=1281&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/03/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-shop-03',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Shop Design 3', 'shopengine'),
            'preview_thumb' => 'contents/shop/03/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=1281&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/03/content.html' : '',
        ],
        [
            'id'            => 'shop-04',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Shop Design 4', 'shopengine'),
            'preview_thumb' => 'contents/shop/04/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=1355&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/04/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-shop-04',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Shop Design 4', 'shopengine'),
            'preview_thumb' => 'contents/shop/04/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=1355&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/04/content.html' : '',
        ],
        [
            'id'            => 'shop-05',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Shop Design 5',
            'preview_thumb' => 'contents/shop/05/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=1417&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/05/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-shop-05',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Shop Design 5',
            'preview_thumb' => 'contents/shop/05/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=1417&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/shop/05/content.html' : '',
        ],
        [
            'id'            => 'shop-06',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Shop Design 6 RTL',
            'preview_thumb' => 'contents/shop/06/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/shop/',
            'file'          => $pro_file ? $pro_file. '/shop/06/content.json' : '',
        ],
    ],
    'cart' => [
        [
            'id'            => 'cart-01',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Cart Design 1', 'shopengine'),
            'preview_thumb' => 'contents/cart/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/cart/?add-to-cart=68',
            'file'          => $free_file ? $free_file. '/cart/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-cart-01',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Cart Design 1', 'shopengine'),
            'preview_thumb' => 'contents/cart/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/cart/?add-to-cart=68',
            'file'          => $free_file ? $free_file. '/cart/01/content.html' : '',
        ],
        [
            'id'            => 'cart-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Cart Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/cart/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/cart/?add-to-cart=70',
            'file'          => $pro_file ? $pro_file. '/cart/02/content.json' : '',
        ],
    ],
    'checkout' => [
        [
            'id'            => 'checkout-01',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Checkout Design 1', 'shopengine'),
            'preview_thumb' => 'contents/checkout/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?add-to-cart=68',
            'file'          => $free_file ? $free_file. '/checkout/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-01',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Checkout Design 1', 'shopengine'),
            'preview_thumb' => 'contents/checkout/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?add-to-cart=68',
            'file'          => $free_file ? $free_file. '/checkout/01/content.html' : '',
        ],
        [
            'id'            => 'checkout-02',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Checkout Design 2', 'shopengine'),
            'preview_thumb' => 'contents/checkout/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3717&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $free_file ? $free_file. '/checkout/02/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-02',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Checkout Design 2', 'shopengine'),
            'preview_thumb' => 'contents/checkout/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3717&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $free_file ? $free_file. '/checkout/02/content.html' : '',
        ],
        [
            'id'            => 'checkout-03',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Checkout Design 3', 'shopengine'),
            'preview_thumb' => 'contents/checkout/03/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3853&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/03/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-03',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Checkout Design 3', 'shopengine'),
            'preview_thumb' => 'contents/checkout/03/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3853&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/03/content.html' : '',
        ],
        [
            'id'            => 'checkout-04',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout Design 4',
            'preview_thumb' => 'contents/checkout/04/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3865&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/04/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-04',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout Design 4',
            'preview_thumb' => 'contents/checkout/04/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3865&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/04/content.html' : '',
        ],
        [
            'id'            => 'checkout-05',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout Design 5',
            'preview_thumb' => 'contents/checkout/05/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=4041&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/05/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-05',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout Design 5',
            'preview_thumb' => 'contents/checkout/05/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=4041&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/05/content.html' : '',
        ],
        [
            'id'            => 'checkout-06',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout Design 6',
            'preview_thumb' => 'contents/checkout/06/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3951&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/06/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-06',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout Design 6',
            'preview_thumb' => 'contents/checkout/06/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=3951&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/06/content.html' : '',
        ],
        [
            'id'            => 'checkout-07',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout Design 7',
            'preview_thumb' => 'contents/checkout/07/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=4018&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/07/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-07',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout Design 7',
            'preview_thumb' => 'contents/checkout/07/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=4018&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/07/content.html' : '',
        ],
        [
            'id'            => 'checkout-08',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout 8',
            'preview_thumb' => 'contents/checkout/08/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1258&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/08/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-08',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout 8',
            'preview_thumb' => 'contents/checkout/08/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1258&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/08/content.html' : '',
        ],
        [
            'id'            => 'checkout-09',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout 9',
            'preview_thumb' => 'contents/checkout/09/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1673&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/09/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-09',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout 9',
            'preview_thumb' => 'contents/checkout/09/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1673&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/09/content.html' : '',
        ],
        [
            'id'            => 'checkout-10',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout 10',
            'preview_thumb' => 'contents/checkout/10/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=821&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/10/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-10',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout 10',
            'preview_thumb' => 'contents/checkout/10/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=821&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/10/content.html' : '',
        ],
        [
            'id'            => 'checkout-11',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout 11',
            'preview_thumb' => 'contents/checkout/11/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1446&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/11/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-11',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout 11',
            'preview_thumb' => 'contents/checkout/11/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1446&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/11/content.html' : '',
        ],
        [
            'id'            => 'checkout-12',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout 12',
            'preview_thumb' => 'contents/checkout/12/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1611&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/12/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-checkout-12',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => 'Checkout 12',
            'preview_thumb' => 'contents/checkout/12/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=1611&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/12/content.html' : '',
        ],
        [
            'id'            => 'checkout-13',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout 13 RTL',
            'preview_thumb' => 'contents/checkout/13/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/checkout/?add-to-cart=70',
            'file'          => $pro_file ? $pro_file. '/checkout/13/content.json' : '',
        ],
        [
            'id'            => 'checkout-14',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => 'Checkout 14 Multistep',
            'preview_thumb' => 'contents/checkout/14/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/?shopengine_template_id=2287&preview_nonce=by_pass_demo&change_template=1&add-to-cart=68',
            'file'          => $pro_file ? $pro_file. '/checkout/14/content.json' : '',
        ],
    ],
    'order' => [
        [
            'id'            => 'order-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Order/Thank You Design 1', 'shopengine'),
            'preview_thumb' => 'contents/order/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/order-received/3665/?key=wc_order_8a7I6ARW3yLVN',
            'file'          => $pro_file ? $pro_file. '/order/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-order-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Order/Thank You Design 1', 'shopengine'),
            'preview_thumb' => 'contents/order/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/checkout/order-received/3665/?key=wc_order_8a7I6ARW3yLVN',
            'file'          => $pro_file ? $pro_file. '/order/01/content.html' : '',
        ],
        [
            'id'            => 'order-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Order/Thank You Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/order/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/checkout/order-received/3826/?key=wc_order_q1FCpiJOQuauI',
            'file'          => $pro_file ? $pro_file. '/order/02/content.json' : '',
        ],
    ],
    'quick_checkout' => [
        [
            'id'            => 'quickcheckout-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Quick Checkout Design 1', 'shopengine'),
            'preview_thumb' => 'contents/quickcheckout/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=613&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/quickcheckout/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-quickcheckout-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Quick Checkout Design 1', 'shopengine'),
            'preview_thumb' => 'contents/quickcheckout/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=613&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/quickcheckout/01/content.html' : '',
        ],
        [
            'id'            => 'quickcheckout-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Quick Checkout Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/quickcheckout/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3880&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/quickcheckout/02/content.json' : '',
        ],
    ],
    'quick_view' => [
        [
            'id'            => 'quickview-01',
            'editor'        => 'elementor',
            'package'       => 'free',
            'title'         => esc_html__('Quickview Design 1', 'shopengine'),
            'preview_thumb' => 'contents/quickview/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=230&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/quickview/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-quickview-01',
            'editor'        => 'gutenberg',
            'package'       => 'free',
            'title'         => esc_html__('Quickview Design 1', 'shopengine'),
            'preview_thumb' => 'contents/quickview/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/?shopengine_template_id=230&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $free_file ? $free_file. '/quickview/01/content.html' : '',
        ],
        [
            'id'            => 'quickview-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Quickview Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/quickview/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3799&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/quickview/02/content.json' : '',
        ],
    ],
    'my_account' => [
        [
            'id'            => 'account-dashboard-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Dashboard Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-dashboard/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/',
            'file'          => $pro_file ? $pro_file. '/account-dashboard/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-account-dashboard-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Account Dashboard Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-dashboard/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/',
            'file'          => $pro_file ? $pro_file. '/account-dashboard/01/content.html' : '',
        ],
        [
            'id'            => 'account-dashboard-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Dashboard Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/account-dashboard/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/my-account/',
            'file'          => $pro_file ? $pro_file. '/account-dashboard/02/content.json' : '',
        ],
    ],
    'account_orders' => [
        [
            'id'            => 'account-orders-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Orders Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-orders/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/orders/',
            'file'          => $pro_file ? $pro_file. '/account-orders/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-account-orders-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Account Orders Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-orders/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/orders/',
            'file'          => $pro_file ? $pro_file. '/account-orders/01/content.html' : '',
        ],
        [
            'id'            => 'account-orders-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Orders Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/account-orders/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3758&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/account-orders/02/content.json' : '',
        ],
    ],
    'account_orders_view' => [
        [
            'id'            => 'account-order-details-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Order Details Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-order-details/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/orders/',
            'file'          => $pro_file ? $pro_file. '/account-order-details/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-account-order-details-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Account Order Details Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-order-details/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/orders/',
            'file'          => $pro_file ? $pro_file. '/account-order-details/01/content.html' : '',
        ],
        [
            'id'            => 'account-order-details-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Order Details Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/account-order-details/02/preview.jpg',
            'demo_url'      => 'https://demo.xpeedstudio.com/bajaar/shopengine-template/account-order-view/',
            'file'          => $pro_file ? $pro_file. '/account-order-details/02/content.json' : '',
        ],
    ],
    'account_downloads' => [
        [
            'id'            => 'account-downloads-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Downloads Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-downloads/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/downloads/',
            'file'          => $pro_file ? $pro_file. '/account-downloads/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-account-downloads-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Account Downloads Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-downloads/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/downloads/',
            'file'          => $pro_file ? $pro_file. '/account-downloads/01/content.html' : '',
        ],
        [
            'id'            => 'account-downloads-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Downloads Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/account-downloads/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3764&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/account-downloads/02/content.json' : '',
        ],
    ],
    'account_edit_address' => [
        [
            'id'            => 'account-address-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Address Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-address/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/edit-address/',
            'file'          => $pro_file ? $pro_file. '/account-address/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-account-address-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Account Address Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-address/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/edit-address/',
            'file'          => $pro_file ? $pro_file. '/account-address/01/content.html' : '',
        ],
        [
            'id'            => 'account-address-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Address Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/account-address/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3767&action=elementor&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/account-address/02/content.json' : '',
        ],
    ],
    'account_edit_account' => [
        [
            'id'            => 'account-details-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Details Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-details/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/edit-account/',
            'file'          => $pro_file ? $pro_file. '/account-details/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-account-details-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Account Details Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-details/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/my-account/edit-account/',
            'file'          => $pro_file ? $pro_file. '/account-details/01/content.html' : '',
        ],
        [
            'id'            => 'account-details-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Details Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/account-details/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3766&action=elementor&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/account-details/02/content.json' : '',
        ],
    ],
    'my_account_login' => [
        [
            'id'            => 'account-login-register-01',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Login/Register Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-login-register/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/shopengine-template/my-account-login-register-default/',
            'file'          => $pro_file ? $pro_file. '/account-login-register/01/content.json' : '',
        ],
        [
            'id'            => 'gutenberg-account-login-register-01',
            'editor'        => 'gutenberg',
            'package'       => 'pro',
            'title'         => esc_html__('Account Login/Register Design 1', 'shopengine'),
            'preview_thumb' => 'contents/account-login-register/01/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/demos/shopengine-template/my-account-login-register-default/',
            'file'          => $pro_file ? $pro_file. '/account-login-register/01/content.html' : '',
        ],
        [
            'id'            => 'account-login-register-02',
            'editor'        => 'elementor',
            'package'       => 'pro',
            'title'         => esc_html__('Account Login/Register Design 2 RTL', 'shopengine'),
            'preview_thumb' => 'contents/account-login-register/02/preview.jpg',
            'demo_url'      => 'https://wpmet.com/plugin/shopengine/rtl/?shopengine_template_id=3744&action=elementor&preview_nonce=by_pass_demo&change_template=1',
            'file'          => $pro_file ? $pro_file. '/account-login-register/02/content.json' : '',
        ],
    ],
];
